-- SESIONES
INSERT INTO INFRA.SESIONES ( ID_DIPLOMADO, SESION, EXPOSITOR,FECHA ) VALUES 
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Cultura organizacional' AND GENERACION = 1 AND YEAR = 2013), 1, 'BIMBO', '2013-02-06' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Cultura organizacional' AND GENERACION = 1 AND YEAR = 2013), 2, 'FEMSA', '2013-02-27' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Cultura organizacional' AND GENERACION = 1 AND YEAR = 2013), 3, 'KCM', '2013-03-20' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Estrategia, planeación e innovación' AND GENERACION = 1 AND YEAR = 2013), 1, 'CEMEX', '2013-02-07' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Estrategia, planeación e innovación' AND GENERACION = 1 AND YEAR = 2013), 2, 'SLR', '2013-03-06' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Estrategia, planeación e innovación' AND GENERACION = 1 AND YEAR = 2013), 3, 'PROEZA', '2013-04-10' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Reducción de costos con manufactura esbelta' AND GENERACION = 1 AND YEAR = 2013), 1, 'DEACERO', '2013-02-14' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Reducción de costos con manufactura esbelta' AND GENERACION = 1 AND YEAR = 2013), 2, 'MABE', '2013-03-13' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Reducción de costos con manufactura esbelta' AND GENERACION = 1 AND YEAR = 2013), 3, 'XIGNUX', '2013-04-02' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Inteligencia comercial' AND GENERACION = 1 AND YEAR = 2013), 1, 'LALA', '2013-02-21' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Inteligencia comercial' AND GENERACION = 1 AND YEAR = 2013), 2, 'BMEX', '2013-03-19' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Inteligencia comercial' AND GENERACION = 1 AND YEAR = 2013), 3, 'GEPP', '2013-04-18' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Inteligencia comercial' AND GENERACION = 1 AND YEAR = 2013), 4, 'MABE', '2013-05-09' );

INSERT INTO INFRA.SESIONES ( ID_DIPLOMADO, SESION, EXPOSITOR,FECHA ) VALUES 
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Cultura organizacional' AND GENERACION = 2 AND YEAR = 2013), 1, 'BIMBO', '2013-04-09' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Cultura organizacional' AND GENERACION = 2 AND YEAR = 2013), 2, 'FEMSA', '2013-05-07' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Cultura organizacional' AND GENERACION = 2 AND YEAR = 2013), 3, 'KCM', '2013-06-04' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Estrategia, planeación e innovación' AND GENERACION = 2 AND YEAR = 2013), 1, 'CEMEX', '2013-04-23' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Estrategia, planeación e innovación' AND GENERACION = 2 AND YEAR = 2013), 2, 'SLR', '2013-05-14' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Estrategia, planeación e innovación' AND GENERACION = 2 AND YEAR = 2013), 3, 'PROEZA', '2013-06-11' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Reducción de costos con manufactura esbelta' AND GENERACION = 2 AND YEAR = 2013), 1, 'DEACERO', '2013-04-30' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Reducción de costos con manufactura esbelta' AND GENERACION = 2 AND YEAR = 2013), 2, 'MABE', '2013-05-21' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Reducción de costos con manufactura esbelta' AND GENERACION = 2 AND YEAR = 2013), 3, 'XIGNUX', '2013-06-18' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Inteligencia comercial' AND GENERACION = 2 AND YEAR = 2013), 1, 'LALA', '2013-05-30' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Inteligencia comercial' AND GENERACION = 2 AND YEAR = 2013), 2, 'BMEX', '2013-06-25' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Inteligencia comercial' AND GENERACION = 2 AND YEAR = 2013), 3, 'GEPP', '2013-07-23' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Inteligencia comercial' AND GENERACION = 2 AND YEAR = 2013), 4, 'MABE', '2013-08-01' );

INSERT INTO INFRA.SESIONES ( ID_DIPLOMADO, SESION, EXPOSITOR,FECHA ) VALUES 
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Cultura organizacional' AND GENERACION = 3 AND YEAR = 2013), 1, 'BIMBO', '2013-07-02' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Cultura organizacional' AND GENERACION = 3 AND YEAR = 2013), 2, 'FEMSA', '2013-07-31' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Cultura organizacional' AND GENERACION = 3 AND YEAR = 2013), 3, 'KCM', '2013-08-20' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Estrategia, planeación e innovación' AND GENERACION = 3 AND YEAR = 2013), 1, 'CEMEX', '2013-07-09' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Estrategia, planeación e innovación' AND GENERACION = 3 AND YEAR = 2013), 2, 'SLR', '2013-08-08' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Estrategia, planeación e innovación' AND GENERACION = 3 AND YEAR = 2013), 3, 'PROEZA', '2013-08-27' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Reducción de costos con manufactura esbelta' AND GENERACION = 3 AND YEAR = 2013), 1, 'DEACERO', '2013-07-18' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Reducción de costos con manufactura esbelta' AND GENERACION = 3 AND YEAR = 2013), 2, 'MABE', '2013-08-15' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Reducción de costos con manufactura esbelta' AND GENERACION = 3 AND YEAR = 2013), 3, 'XIGNUX', '2013-09-12' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Inteligencia comercial' AND GENERACION = 3 AND YEAR = 2013), 1, 'LALA', '2013-07-25' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Inteligencia comercial' AND GENERACION = 3 AND YEAR = 2013), 2, 'BMEX', '2013-08-29' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Inteligencia comercial' AND GENERACION = 3 AND YEAR = 2013), 3, 'GEPP', '2013-09-24' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Inteligencia comercial' AND GENERACION = 3 AND YEAR = 2013), 4, 'MABE', '2013-10-17' );

INSERT INTO INFRA.SESIONES ( ID_DIPLOMADO, SESION, EXPOSITOR,FECHA ) VALUES 
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Cultura organizacional' AND GENERACION = 4 AND YEAR = 2013), 1, 'BIMBO', '2013-09-04' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Cultura organizacional' AND GENERACION = 4 AND YEAR = 2013), 2, 'FEMSA', '2013-10-01' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Cultura organizacional' AND GENERACION = 4 AND YEAR = 2013), 3, 'KCM', '2013-10-29' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Estrategia, planeación e innovación' AND GENERACION = 4 AND YEAR = 2013), 1, 'CEMEX', '2013-09-01' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Estrategia, planeación e innovación' AND GENERACION = 4 AND YEAR = 2013), 2, 'SLR', '2013-10-08' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Estrategia, planeación e innovación' AND GENERACION = 4 AND YEAR = 2013), 3, 'PROEZA', '2013-11-05' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Reducción de costos con manufactura esbelta' AND GENERACION = 4 AND YEAR = 2013), 1, 'DEACERO', '2013-09-17' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Reducción de costos con manufactura esbelta' AND GENERACION = 4 AND YEAR = 2013), 2, 'MABE', '2013-10-15' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Reducción de costos con manufactura esbelta' AND GENERACION = 4 AND YEAR = 2013), 3, 'XIGNUX', '2013-11-12' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Inteligencia comercial' AND GENERACION = 4 AND YEAR = 2013), 1, 'LALA', '2013-09-26' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Inteligencia comercial' AND GENERACION = 4 AND YEAR = 2013), 2, 'BMEX', '2013-10-24' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Inteligencia comercial' AND GENERACION = 4 AND YEAR = 2013), 3, 'GEPP', '2013-11-19' ),
( (SELECT ID_DIPLOMADO FROM INFRA.DIPLOMADOS WHERE TEMA = 'Inteligencia comercial' AND GENERACION = 4 AND YEAR = 2013), 3, 'MABE', '2013-11-26' );