--Insert consultora y consultor
--1
INSERT INTO INFRA.USUARIOS ( CVE_USUARIO, PASSWORD ) VALUES( 'dummy.consultora.1@mail.com', 'ccmx1234' );
INSERT INTO INFRA.REL_ROLES ( CVE_ROL, CVE_USUARIO ) VALUES( 'AdministradorConsultores', 'dummy.consultora.1@mail.com' );
INSERT INTO INFRA.CONSULTORAS ( ID_USUARIO, ID_USUARIO_PADRE,ID_CONSULTORA_PADRE,EMPRESA, NOMBRE_CONTACTO, APP_PATERNO_CONTACTO, CORREO_ELECTRONICO_CONTACTO ) 
VALUES(( SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'dummy.consultora.1@mail.com' ), 1, 0,'G. Valdes', 'Dummy', 'Dummy', 'dummy.consultora.1@mail.com' );

INSERT INTO INFRA.USUARIOS ( CVE_USUARIO, PASSWORD ) VALUES( 'dummy.consultor.1@mail.com', 'ccmx1234' );
INSERT INTO INFRA.REL_ROLES ( CVE_ROL, CVE_USUARIO ) VALUES( 'Consultor', 'dummy.consultor.1@mail.com' );
INSERT INTO INFRA.CONSULTORAS ( ID_USUARIO, ID_USUARIO_PADRE,ID_CONSULTORA_PADRE,EMPRESA, NOMBRE_CONTACTO, APP_PATERNO_CONTACTO, CORREO_ELECTRONICO_CONTACTO ) 
VALUES(( SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'dummy.consultor.1@mail.com' ), 1, ( SELECT ID_CONSULTORA FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' ),'G. Valdes', 'Dummy', 'Dummy', 'dummy.consultor.1@mail.com' );


--2
INSERT INTO INFRA.USUARIOS ( CVE_USUARIO, PASSWORD ) VALUES( 'dummy.consultora.2@mail.com', 'ccmx1234' );
INSERT INTO INFRA.REL_ROLES ( CVE_ROL, CVE_USUARIO ) VALUES( 'AdministradorConsultores', 'dummy.consultora.2@mail.com' );
INSERT INTO INFRA.CONSULTORAS ( ID_USUARIO, ID_USUARIO_PADRE,ID_CONSULTORA_PADRE,EMPRESA, NOMBRE_CONTACTO, APP_PATERNO_CONTACTO, CORREO_ELECTRONICO_CONTACTO ) 
VALUES(( SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'dummy.consultora.2@mail.com' ), 1, 0,'Crece Gto.', 'Dummy', 'Dummy', 'dummy.consultora.2@mail.com' );

INSERT INTO INFRA.USUARIOS ( CVE_USUARIO, PASSWORD ) VALUES( 'dummy.consultor.2@mail.com', 'ccmx1234' );
INSERT INTO INFRA.REL_ROLES ( CVE_ROL, CVE_USUARIO ) VALUES( 'Consultor', 'dummy.consultor.2@mail.com' );
INSERT INTO INFRA.CONSULTORAS ( ID_USUARIO, ID_USUARIO_PADRE,ID_CONSULTORA_PADRE,EMPRESA, NOMBRE_CONTACTO, APP_PATERNO_CONTACTO, CORREO_ELECTRONICO_CONTACTO ) 
VALUES(( SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'dummy.consultor.2@mail.com' ), 1, ( SELECT ID_CONSULTORA FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' ),'Crece Gto.', 'Dummy', 'Dummy', 'dummy.consultor.2@mail.com' );


--3
INSERT INTO INFRA.USUARIOS ( CVE_USUARIO, PASSWORD ) VALUES( 'dummy.consultora.3@mail.com', 'ccmx1234' );
INSERT INTO INFRA.REL_ROLES ( CVE_ROL, CVE_USUARIO ) VALUES( 'AdministradorConsultores', 'dummy.consultora.3@mail.com' );
INSERT INTO INFRA.CONSULTORAS ( ID_USUARIO, ID_USUARIO_PADRE,ID_CONSULTORA_PADRE,EMPRESA, NOMBRE_CONTACTO, APP_PATERNO_CONTACTO, CORREO_ELECTRONICO_CONTACTO ) 
VALUES(( SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'dummy.consultora.3@mail.com' ), 1, 0,'Fundes', 'Dummy', 'Dummy', 'dummy.consultora.3@mail.com' );

INSERT INTO INFRA.USUARIOS ( CVE_USUARIO, PASSWORD ) VALUES( 'dummy.consultor.3@mail.com', 'ccmx1234' );
INSERT INTO INFRA.REL_ROLES ( CVE_ROL, CVE_USUARIO ) VALUES( 'Consultor', 'dummy.consultor.3@mail.com' );
INSERT INTO INFRA.CONSULTORAS ( ID_USUARIO, ID_USUARIO_PADRE,ID_CONSULTORA_PADRE,EMPRESA, NOMBRE_CONTACTO, APP_PATERNO_CONTACTO, CORREO_ELECTRONICO_CONTACTO ) 
VALUES(( SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'dummy.consultor.3@mail.com' ), 1, ( SELECT ID_CONSULTORA FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' ),'Fundes', 'Dummy', 'Dummy', 'dummy.consultor.3@mail.com' );

--4
INSERT INTO INFRA.USUARIOS ( CVE_USUARIO, PASSWORD ) VALUES( 'dummy.consultora.4@mail.com', 'ccmx1234' );
INSERT INTO INFRA.REL_ROLES ( CVE_ROL, CVE_USUARIO ) VALUES( 'AdministradorConsultores', 'dummy.consultora.4@mail.com' );
INSERT INTO INFRA.CONSULTORAS ( ID_USUARIO, ID_USUARIO_PADRE,ID_CONSULTORA_PADRE,EMPRESA, NOMBRE_CONTACTO, APP_PATERNO_CONTACTO, CORREO_ELECTRONICO_CONTACTO ) 
VALUES(( SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'dummy.consultora.4@mail.com' ), 1, 0,'MB entrenamiento', 'Dummy', 'Dummy', 'dummy.consultora.4@mail.com' );

INSERT INTO INFRA.USUARIOS ( CVE_USUARIO, PASSWORD ) VALUES( 'dummy.consultor.4@mail.com', 'ccmx1234' );
INSERT INTO INFRA.REL_ROLES ( CVE_ROL, CVE_USUARIO ) VALUES( 'Consultor', 'dummy.consultor.4@mail.com' );
INSERT INTO INFRA.CONSULTORAS ( ID_USUARIO, ID_USUARIO_PADRE,ID_CONSULTORA_PADRE,EMPRESA, NOMBRE_CONTACTO, APP_PATERNO_CONTACTO, CORREO_ELECTRONICO_CONTACTO ) 
VALUES(( SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'dummy.consultor.4@mail.com' ), 1, ( SELECT ID_CONSULTORA FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.4@mail.com' ),'MB entrenamiento', 'Dummy', 'Dummy', 'dummy.consultor.4@mail.com' );


--5
INSERT INTO INFRA.USUARIOS ( CVE_USUARIO, PASSWORD ) VALUES( 'dummy.consultora.5@mail.com', 'ccmx1234' );
INSERT INTO INFRA.REL_ROLES ( CVE_ROL, CVE_USUARIO ) VALUES( 'AdministradorConsultores', 'dummy.consultora.5@mail.com' );
INSERT INTO INFRA.CONSULTORAS ( ID_USUARIO, ID_USUARIO_PADRE,ID_CONSULTORA_PADRE,EMPRESA, NOMBRE_CONTACTO, APP_PATERNO_CONTACTO, CORREO_ELECTRONICO_CONTACTO ) 
VALUES(( SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'dummy.consultora.5@mail.com' ), 1, 0,'MB entrenamiento', 'Dummy', 'Dummy', 'dummy.consultora.5@mail.com' );

INSERT INTO INFRA.USUARIOS ( CVE_USUARIO, PASSWORD ) VALUES( 'dummy.consultor.5@mail.com', 'ccmx1234' );
INSERT INTO INFRA.REL_ROLES ( CVE_ROL, CVE_USUARIO ) VALUES( 'Consultor', 'dummy.consultor.5@mail.com' );
INSERT INTO INFRA.CONSULTORAS ( ID_USUARIO, ID_USUARIO_PADRE,ID_CONSULTORA_PADRE,EMPRESA, NOMBRE_CONTACTO, APP_PATERNO_CONTACTO, CORREO_ELECTRONICO_CONTACTO ) 
VALUES(( SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'dummy.consultor.5@mail.com' ), 1, ( SELECT ID_CONSULTORA FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.5@mail.com' ),'MB entrenamiento', 'Dummy', 'Dummy', 'dummy.consultor.5@mail.com' );


--Relacion Pymes
--1
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'daniel@dicilab.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'daniel@dicilab.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));


INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'marco.flores@innovaseals.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'marco.flores@innovaseals.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'albiosan@live.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'albiosan@live.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'emercado@espacios-ingenieria.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'emercado@espacios-ingenieria.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'direccion@michelconstrucciones.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'direccion@michelconstrucciones.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'lmolina@grupomolina.org'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'lmolina@grupomolina.org'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'h_distribuidora@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'h_distribuidora@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'fps@mbm.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'fps@mbm.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'mmuam@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'mmuam@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'abner@hsoluciones.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'abner@hsoluciones.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'connie.alvarez@digitaldruck.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'connie.alvarez@digitaldruck.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'jleyva@liquibox.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'jleyva@liquibox.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'robertolc@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'robertolc@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'maquinaria.ares@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'maquinaria.ares@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'efrainmartinez@harocontrol.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'efrainmartinez@harocontrol.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'navarrotql@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'navarrotql@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'fibraxotzil@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'fibraxotzil@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'tallpe_epm@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'tallpe_epm@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ventasserviciosyproyectos@reypco.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ventasserviciosyproyectos@reypco.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'hiel_misionera@mexico.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'hiel_misionera@mexico.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'santiago.macias@productossangabriel.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'santiago.macias@productossangabriel.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'rtl2002@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'rtl2002@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'jorgegaribay@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'jorgegaribay@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'mquezada.proimia@megared.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'mquezada.proimia@megared.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'corinsa@live.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'corinsa@live.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'contraloria@superwetplus.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'contraloria@superwetplus.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'oymcomunicacion@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'oymcomunicacion@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'angelospromos@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'angelospromos@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'equiposdemedicion@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'equiposdemedicion@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'daniel@uyeda.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'daniel@uyeda.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ricardoorr@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ricardoorr@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ingenieriaintegral@att.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ingenieriaintegral@att.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'socorrelepe@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'socorrelepe@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'consupapeleria@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'consupapeleria@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'materialeselectricos_1@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'materialeselectricos_1@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'cercaplus@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'cercaplus@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'federico.quintero@dynonobel.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'federico.quintero@dynonobel.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'echegollen@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'echegollen@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'venturaa@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'venturaa@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));


INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'gav@awasa.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'gav@awasa.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'amaliaparedes@mac.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'amaliaparedes@mac.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'gteadministrativo@provejal.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'gteadministrativo@provejal.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'antoniojaramillo@tema.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'antoniojaramillo@tema.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'socorrovictoria@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'socorrovictoria@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'lilianaperez.egar@gmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'lilianaperez.egar@gmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));


INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ciapmet@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ciapmet@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));


INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'jaime.sahagun@lubriagsa.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'jaime.sahagun@lubriagsa.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'amedinilla@agromega.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'amedinilla@agromega.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'padilla77_7@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'padilla77_7@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'jarenas@sicosa.net'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'jarenas@sicosa.net'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'impresoselangel@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'impresoselangel@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'gabriela.gomez@amher.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'gabriela.gomez@amher.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'javierar_wetpeak@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'javierar_wetpeak@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'mariaeugenia.montana@zuritaindustrial.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'mariaeugenia.montana@zuritaindustrial.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'jesusochoa183@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'jesusochoa183@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'graficos_impresores@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'graficos_impresores@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'direccion@fibrakania.net'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'direccion@fibrakania.net'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'malcaraz@imprerapid.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'malcaraz@imprerapid.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'dr.rex@live.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'dr.rex@live.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'macrovolta@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'macrovolta@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'arturoa@albe.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'arturoa@albe.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'info@ipharma.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'info@ipharma.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'marcos@metmar.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'marcos@metmar.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'gera_edemon@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'gera_edemon@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'administracion@macoba.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'administracion@macoba.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'habarca@tizhak.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'habarca@tizhak.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'maquinados68@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'maquinados68@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ventas@pacosa.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ventas@pacosa.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'gakita@jaloma.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'gakita@jaloma.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'adrianasantosmx@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'adrianasantosmx@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'octavio@erco.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'octavio@erco.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ep.promociones@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ep.promociones@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'miguel.acosta@nartexlabs.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'miguel.acosta@nartexlabs.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'marketing@amenijal.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'marketing@amenijal.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'mryepez@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'mryepez@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'jbonilla@globaloffice.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'jbonilla@globaloffice.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ingesparza355@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ingesparza355@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'dimetal.sa@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'dimetal.sa@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'aguapotable_5@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'aguapotable_5@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'alex@alpier.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'alex@alpier.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));


INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'mymindustriales@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'mymindustriales@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'faahrenheit@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'faahrenheit@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'mecsagdl@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'mecsagdl@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'felicitascasillas@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'felicitascasillas@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'resortes_uni@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'resortes_uni@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'blanca.ventas@byparsa.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'blanca.ventas@byparsa.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'inveduc@live.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'inveduc@live.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'jgpe070360@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.1@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'jgpe070360@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.1@mail.com' ));



----2
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'indnavar@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'indnavar@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'rfernandezt@prefinsa.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'rfernandezt@prefinsa.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'eguerrero@comrisa.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'eguerrero@comrisa.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'aj@arquiplanos.net'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'aj@arquiplanos.net'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'hotmelt@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'hotmelt@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'luna_idc@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'luna_idc@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'jaime20032011@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'jaime20032011@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'falcantara@compresoresalemanes.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'falcantara@compresoresalemanes.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'victoripz-me@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'victoripz-me@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'clave_08@claveconstrucciones.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'clave_08@claveconstrucciones.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'rlsramirez@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'rlsramirez@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'daisaind@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'daisaind@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'mnegrete@idihsa.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'mnegrete@idihsa.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'jcfernandez@betma.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'jcfernandez@betma.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'rivera_oscar@live.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'rivera_oscar@live.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'zamek80@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'zamek80@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'quimivisa@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'quimivisa@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'gerardo_rioja@live.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'gerardo_rioja@live.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'claudia.derramadero@tei-mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'claudia.derramadero@tei-mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'suministrosdeplasticos@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'suministrosdeplasticos@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'multiferreteraind@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'multiferreteraind@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'bacilio.bylhnos@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'bacilio.bylhnos@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'hurtado.hupesa_guadalupe@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'hurtado.hupesa_guadalupe@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ezequielho@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ezequielho@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'lander87_87@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'lander87_87@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'buchin@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'buchin@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'salazarmendezc@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'salazarmendezc@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'estroandan@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'estroandan@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'maquifelix@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.2@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'maquifelix@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.2@mail.com' ));


----3
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'alejandro_roblesg@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'alejandro_roblesg@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'paznikko@herramientassanders.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'paznikko@herramientassanders.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'industrial_lule@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'industrial_lule@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'juniorpitts@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'juniorpitts@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'sfahtas@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'sfahtas@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'aeecsa@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'aeecsa@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'vulcanizador_tecnicos@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'vulcanizador_tecnicos@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'eorozco@grupofiestafood.net'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'eorozco@grupofiestafood.net'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'elmetro@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'elmetro@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ireca_@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ireca_@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'chasa_huerta@live.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'chasa_huerta@live.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'garitamaquinados@gmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'garitamaquinados@gmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));


INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'webmaster@gvymisa.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'webmaster@gvymisa.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'galcorta@grupogarze.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'galcorta@grupogarze.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));


INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'hclavijo@policauchoindustrial.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'hclavijo@policauchoindustrial.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'modi54@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'modi54@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ingservio@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ingservio@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'rruelas@hemi.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'rruelas@hemi.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'adolfoluna@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'adolfoluna@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 't_credi@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 't_credi@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));


INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'saul.mgavia@gmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'saul.mgavia@gmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));


INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'sbanos@emmexa.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'sbanos@emmexa.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'grupoimpresor@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'grupoimpresor@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'lnuñez@jonsa.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'lnuñez@jonsa.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'accegind@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'accegind@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'info@tocira.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'info@tocira.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ricardo@troquelesthr.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'ricardo@troquelesthr.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'bguerrero@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'bguerrero@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'irsmetallizing@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'irsmetallizing@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'smiletreros@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'smiletreros@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'capese@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'capese@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'sherebe@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'sherebe@prodigy.net.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'beltro17@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'beltro17@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'edith2412@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'edith2412@yahoo.com.mx'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'jolurios@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'jolurios@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));

INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'alf_po@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultora.3@mail.com' )
);
INSERT INTO INFRA.REL_CONSULTORAS_PYME(ID_USUARIO_PYME,ID_USUARIO_CONSULTOR) VALUES(
(SELECT ID_USUARIO FROM INFRA.USUARIOS WHERE CVE_USUARIO = 'alf_po@hotmail.com'),
(SELECT ID_USUARIO FROM INFRA.CONSULTORAS WHERE CORREO_ELECTRONICO_CONTACTO = 'dummy.consultor.3@mail.com' ));
